# Generated by Django 3.1 on 2020-09-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='图片地址'),
        ),
    ]
