# Generated by Django 3.1 on 2020-09-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='发布日期'),
        ),
    ]
