# Generated by Django 3.1 on 2020-09-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='target_person_details',
            field=models.TextField(max_length=255, verbose_name='目标人群详情'),
        ),
    ]
