# Generated by Django 3.1 on 2020-08-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200827_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_url',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='image'),
        ),
    ]
