# Generated by Django 3.1 on 2020-08-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('video', models.CharField(max_length=255, verbose_name='视频地址')),
                ('time', models.IntegerField(default=0, verbose_name='时长')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('free', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='免费')),
                ('published', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='发布')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
                'db_table': 'chapters',
            },
        ),
    ]
